import type { Tool } from '../types'

function tool(partial: Omit<Tool, 'created_at'> & { created_at?: string }): Tool {
  return {
    created_at: '2026-03-12T10:00:00.000Z',
    ...partial,
  }
}

export const DEMO_TOOLS: Tool[] = [
  tool({
    id: 1,
    name: 'Omarchy',
    url: 'omarchy',
    description: 'An opinionated Arch Linux distribution based on Hyprland, ready to use the moment it boots.',
    category: 'Developer Tools',
    homepage: 'https://omarchy.org/',
    github_url: 'https://github.com/omacom/omarchy',
    docs_url: 'https://omarchy.org/manual/',
    what_it_is: 'Omarchy is a preconfigured Arch Linux system built around Hyprland and a curated app stack. It ships Neovim, a terminal-first workflow, and theming so you skip weeks of ricing.',
    why_it_exists: 'Linux setups are powerful but slow to make beautiful and productive. Omarchy is the omakase option: tasteful defaults, immediate productivity.',
    features: [
      'Preconfigured Arch + Hyprland desktop',
      'Curated terminal-first app stack',
      'Extensive theming and hotkeys',
      'Zero-setup developer environment',
    ],
    when_to_use: [
      'You want a working Linux desktop without a weekend of config',
      'You prefer tiling window managers and the terminal',
    ],
    when_not_to_use: [
      'You need a beginner-friendly graphical installer only',
      'You want a Windows or macOS clone',
    ],
    tags: ['linux', 'arch', 'hyprland', 'open-source', 'developer-tools'],
  }),
  tool({
    id: 2,
    name: 'Ventoy',
    url: 'ventoy',
    description: 'Open-source tool for creating a bootable USB that holds many ISOs at once — drop files in, boot the menu.',
    category: 'Developer Tools',
    homepage: 'https://www.ventoy.net/en/index.html',
    github_url: 'https://github.com/ventoy/Ventoy',
    docs_url: 'https://www.ventoy.net/en/doc_start.html',
    what_it_is: 'Ventoy turns a USB drive into a multi-ISO boot menu. Copy ISO, WIM, IMG, VHD(x) or EFI files onto the disk; no reformat per image.',
    why_it_exists: 'Rewriting a USB for every distro or Windows installer is tedious. Ventoy lets one stick carry a whole lab of boot media.',
    features: [
      'Boot multiple ISOs from one USB',
      'MBR and GPT support',
      'Secure Boot compatible in many setups',
      'No need to reformat when adding images',
    ],
    when_to_use: [
      'Installing or testing several operating systems',
      'Keeping rescue and installer media on one drive',
    ],
    when_not_to_use: [
      'You only ever boot a single image',
      'The target firmware is unusually picky about bootloaders',
    ],
    tags: ['usb', 'iso', 'boot', 'open-source', 'sysadmin'],
  }),
  tool({
    id: 3,
    name: 'Jellyfin',
    url: 'jellyfin',
    description: 'Free, open-source media server for organizing and streaming your movies, shows, music, and photos.',
    category: 'Content Creation',
    homepage: 'https://jellyfin.org',
    github_url: 'https://github.com/jellyfin/jellyfin',
    docs_url: 'https://jellyfin.org/docs',
    what_it_is: 'Jellyfin is a self-hosted media platform with apps for TVs, phones, and browsers. No tracking, no premium tier.',
    why_it_exists: 'People want Plex-like libraries without a vendor account or paid features gated behind a login.',
    features: [
      'Hardware-accelerated transcoding',
      'Live TV and DVR plugins',
      'Clients for most platforms',
      'No mandatory cloud account',
    ],
    when_to_use: [
      'You already own a media library and a home server',
      'You want streaming without a subscription',
    ],
    when_not_to_use: [
      'You prefer a fully managed cloud service',
      'You do not want to run a server',
    ],
    tags: ['media', 'self-hosted', 'open-source', 'streaming'],
  }),
  tool({
    id: 4,
    name: 'Hyprland',
    url: 'hyprland',
    description: 'Dynamic tiling Wayland compositor with smooth animations, eye candy, and a powerful config language.',
    category: 'Developer Tools',
    homepage: 'https://hypr.land',
    github_url: 'https://github.com/hyprwm/Hyprland',
    docs_url: 'https://wiki.hypr.land',
    what_it_is: 'Hyprland is a Wayland compositor focused on looks and control. Windows tile automatically; gaps, blur, and animations are first-class.',
    why_it_exists: 'Older tiling WMs felt dated on Wayland. Hyprland made a modern, scriptable compositor that still feels fast.',
    features: [
      'Dynamic tiling on Wayland',
      'Built-in animations and blur',
      'Socket IPC and extensive config',
      'Plugin ecosystem',
    ],
    when_to_use: [
      'You want a tiling workflow on a modern Linux desktop',
      'You enjoy tuning every visual detail',
    ],
    when_not_to_use: [
      'You need a batteries-included desktop like GNOME',
      'Your GPU or drivers fight Wayland',
    ],
    tags: ['linux', 'wayland', 'tiling', 'open-source'],
  }),
  tool({
    id: 5,
    name: 'Ghostty',
    url: 'ghostty',
    description: 'Fast, native GPU terminal emulator with sensible defaults and first-class platform integration.',
    category: 'Developer Tools',
    homepage: 'https://ghostty.org',
    github_url: 'https://github.com/ghostty-org/ghostty',
    docs_url: 'https://ghostty.org/docs',
    what_it_is: 'Ghostty is a terminal that aims to be both fast and native on macOS and Linux, without a cross-platform UI toolkit tax.',
    why_it_exists: 'Many terminals force a tradeoff between speed, features, and looking like they belong on the OS. Ghostty targets all three.',
    features: [
      'GPU-accelerated rendering',
      'Native tabs and windows',
      'Ligatures and rich font features',
      'Cross-platform with native feel',
    ],
    when_to_use: [
      'Daily terminal work where latency matters',
      'You want a modern default that still feels native',
    ],
    when_not_to_use: [
      'You need a terminal that runs everywhere including Windows today',
      'You rely on a very specific plugin from another emulator',
    ],
    tags: ['terminal', 'gpu', 'cli', 'open-source'],
  }),
  tool({
    id: 6,
    name: 'Portainer',
    url: 'portainer',
    description: 'Lightweight UI for managing Docker, Swarm, Kubernetes, and edge containers from a browser.',
    category: 'DevOps & Infrastructure',
    homepage: 'https://www.portainer.io',
    github_url: 'https://github.com/portainer/portainer',
    docs_url: 'https://docs.portainer.io',
    what_it_is: 'Portainer is a web UI over container runtimes. Stacks, images, volumes, and RBAC without living in the CLI.',
    why_it_exists: 'Container ops are powerful and easy to get wrong. A visual layer helps homelabs and teams inspect what is running.',
    features: [
      'Docker and Kubernetes support',
      'Stack deploy from Compose',
      'User access control',
      'Edge agent for remote nodes',
    ],
    when_to_use: [
      'You run several containers and want a dashboard',
      'You share a homelab and need simple RBAC',
    ],
    when_not_to_use: [
      'You already live in kubectl and never want a UI',
      'You need a full GitOps control plane',
    ],
    tags: ['docker', 'kubernetes', 'self-hosted', 'devops'],
  }),
  tool({
    id: 7,
    name: 'Ollama',
    url: 'ollama',
    description: 'Run open large language models locally with a simple CLI and HTTP API.',
    category: 'AI/ML',
    homepage: 'https://ollama.com',
    github_url: 'https://github.com/ollama/ollama',
    docs_url: 'https://github.com/ollama/ollama/blob/main/docs/README.md',
    what_it_is: 'Ollama packages model weights, a runner, and an OpenAI-compatible API so you can `ollama run` on a laptop or server.',
    why_it_exists: 'Cloud LLMs are great until privacy, cost, or offline access matter. Ollama made local models as easy as pulling a container.',
    features: [
      'One-command model pulls',
      'OpenAI-compatible API',
      'Tool calling on supported models',
      'GPU and CPU inference',
    ],
    when_to_use: [
      'You want private or offline LLM inference',
      'You are prototyping agents against a local endpoint',
    ],
    when_not_to_use: [
      'You need frontier-quality models with no hardware',
      'You only want a hosted chat UI with no ops',
    ],
    tags: ['llm', 'local-ai', 'open-source', 'cli'],
  }),
  tool({
    id: 8,
    name: 'Raycast',
    url: 'raycast',
    description: 'Extensible launcher for macOS: apps, snippets, windows, AI, and a huge extension store.',
    category: 'Productivity',
    homepage: 'https://www.raycast.com',
    github_url: 'https://github.com/raycast/extensions',
    docs_url: 'https://developers.raycast.com',
    what_it_is: 'Raycast replaces Spotlight with a fast command palette, clipboard history, window management, and community extensions.',
    why_it_exists: 'macOS search is fine until you live in shortcuts. Raycast is the launcher people keep after they try it for a week.',
    features: [
      'Fuzzy app and command search',
      'Clipboard and snippet history',
      'Window management',
      'AI commands and extensions',
    ],
    when_to_use: [
      'You work on a Mac and want everything a keystroke away',
      'Your team shares internal extensions',
    ],
    when_not_to_use: [
      'You are not on macOS',
      'You only need a simple app launcher',
    ],
    tags: ['macos', 'launcher', 'productivity', 'extensions'],
  }),
]
